# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Nguyen, Dinh Bien
title: Information and Technology Student
email: ctf.d3s34@gmail.com
website: https://ctf.d3s34.me/

# Social links
#twitter_username: facespics
github_username:  biennd279
# dribbble_username: jekyll
facebook_username: biennd.279
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: bien-n-310b24130
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title:
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  - 🌱 I’m currently learning at FIT, University of Engineering and Techlonogy, Vietnam National University.
  - 💬 Ask me about Cyber Security
  - 📫 How to reach me: ctf.d3s34@gmail.com
  - 🕮 I'm writing blog at https://ctf.d3s34.me/, https://d3s34.me/


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
